export interface Employee {
  employeeId: number;
  name: string;
  designation: string;
  phoneNumber: number;
  address: string;
  supervisorName: string;
}

export const employees: Employee[] = [
  {
    employeeId: 1,
    name: 'Charlie Chaplin',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 2,
    name: 'Bob Henry',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 3,
    name: 'Charles Xavier',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 4,
    name: 'Scott Alen',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 5,
    name: 'Alex Decousta',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 6,
    name: 'Emma Deux',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 7,
    name: 'Henry Miller',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 8,
    name: 'Charlie Spicemen',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 9,
    name: 'Harley Quinn',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 10,
    name: 'Tom Henny',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Steve",
  },
  {
    employeeId: 11,
    name: 'Tony',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 12,
    name: 'Tim Joe',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 13,
    name: 'Scotty Pablo',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 14,
    name: 'Eloni',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 15,
    name: 'Emily',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 16,
    name: 'Charles Desouza',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 17,
    name: 'Hammer Wormy',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 18,
    name: 'Bradd',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 19,
    name: 'Hilton Milton',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
  {
    employeeId: 20,
    name: 'Amex Miller',
    designation: 'Software Developer',
    phoneNumber: 9988060,
    address: 'St. Marry School, Chandigarh.',
    supervisorName: "Evan",
  },
];
